export const OTHER = "أخرى";

export type ModelSpec = { colors: string[]; storages: string[] };
export type FullCatalog = Record<string, Record<string, Record<string, ModelSpec>>>;

export const CATALOG: FullCatalog = {
  "Apple": {
    "iPhone": {
      "iPhone 17 Pro Max":  { colors: ["Desert Titanium","Black Titanium","White Titanium","Natural Titanium"], storages: ["256GB","512GB","1TB"] },
      "iPhone 17 Pro":      { colors: ["Desert Titanium","Black Titanium","White Titanium","Natural Titanium"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 17 Air":      { colors: ["Sky Blue","Black","White","Ultramarine"], storages: ["128GB","256GB","512GB"] },
      "iPhone 17":          { colors: ["Black","White","Ultramarine","Teal","Pink"], storages: ["128GB","256GB","512GB"] },
      "iPhone 16 Pro Max":  { colors: ["Desert Titanium","Black Titanium","White Titanium","Natural Titanium"], storages: ["256GB","512GB","1TB"] },
      "iPhone 16 Pro":      { colors: ["Desert Titanium","Black Titanium","White Titanium","Natural Titanium"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 16 Plus":     { colors: ["Black","White","Pink","Teal","Ultramarine"], storages: ["128GB","256GB","512GB"] },
      "iPhone 16":          { colors: ["Black","White","Pink","Teal","Ultramarine"], storages: ["128GB","256GB","512GB"] },
      "iPhone 15 Pro Max":  { colors: ["Black Titanium","White Titanium","Blue Titanium","Natural Titanium"], storages: ["256GB","512GB","1TB"] },
      "iPhone 15 Pro":      { colors: ["Black Titanium","White Titanium","Blue Titanium","Natural Titanium"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 15 Plus":     { colors: ["Black","Blue","Green","Yellow","Pink"], storages: ["128GB","256GB","512GB"] },
      "iPhone 15":          { colors: ["Black","Blue","Green","Yellow","Pink"], storages: ["128GB","256GB","512GB"] },
      "iPhone 14 Pro Max":  { colors: ["Deep Purple","Gold","Silver","Space Black"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 14 Pro":      { colors: ["Deep Purple","Gold","Silver","Space Black"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 14 Plus":     { colors: ["Midnight","Starlight","Blue","Purple","Yellow","Red"], storages: ["128GB","256GB","512GB"] },
      "iPhone 14":          { colors: ["Midnight","Starlight","Blue","Purple","Yellow","Red"], storages: ["128GB","256GB","512GB"] },
      "iPhone 13 Pro Max":  { colors: ["Sierra Blue","Silver","Gold","Alpine Green","Graphite"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 13 Pro":      { colors: ["Sierra Blue","Silver","Gold","Alpine Green","Graphite"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPhone 13 mini":     { colors: ["Midnight","Starlight","Blue","Pink","Green","Red"], storages: ["128GB","256GB","512GB"] },
      "iPhone 13":          { colors: ["Midnight","Starlight","Blue","Pink","Green","Red"], storages: ["128GB","256GB","512GB"] },
      "iPhone 12 Pro Max":  { colors: ["Pacific Blue","Gold","Silver","Graphite"], storages: ["128GB","256GB","512GB"] },
      "iPhone 12 Pro":      { colors: ["Pacific Blue","Gold","Silver","Graphite"], storages: ["128GB","256GB","512GB"] },
      "iPhone 12 mini":     { colors: ["Black","White","Red","Blue","Green","Purple"], storages: ["64GB","128GB","256GB"] },
      "iPhone 12":          { colors: ["Black","White","Red","Blue","Green","Purple"], storages: ["64GB","128GB","256GB"] },
      "iPhone 11 Pro Max":  { colors: ["Midnight Green","Gold","Silver","Space Gray"], storages: ["64GB","256GB","512GB"] },
      "iPhone 11 Pro":      { colors: ["Midnight Green","Gold","Silver","Space Gray"], storages: ["64GB","256GB","512GB"] },
      "iPhone 11":          { colors: ["Black","White","Yellow","Purple","Green","Red"], storages: ["64GB","128GB","256GB"] },
      "iPhone XS Max":      { colors: ["Gold","Silver","Space Gray"], storages: ["64GB","256GB","512GB"] },
      "iPhone XS":          { colors: ["Gold","Silver","Space Gray"], storages: ["64GB","256GB","512GB"] },
      "iPhone XR":          { colors: ["Black","White","Blue","Yellow","Coral","Red"], storages: ["64GB","128GB","256GB"] },
      "iPhone X":           { colors: ["Silver","Space Gray"], storages: ["64GB","256GB"] },
      "iPhone 8 Plus":      { colors: ["Gold","Silver","Space Gray","Red"], storages: ["64GB","128GB","256GB"] },
      "iPhone 8":           { colors: ["Gold","Silver","Space Gray","Red"], storages: ["64GB","128GB","256GB"] },
      "iPhone 7 Plus":      { colors: ["Jet Black","Matte Black","Gold","Silver","Rose Gold","Red"], storages: ["32GB","128GB","256GB"] },
      "iPhone 7":           { colors: ["Jet Black","Matte Black","Gold","Silver","Rose Gold","Red"], storages: ["32GB","128GB","256GB"] },
      "iPhone 6s Plus":     { colors: ["Gold","Silver","Space Gray","Rose Gold"], storages: ["16GB","32GB","64GB","128GB"] },
      "iPhone 6s":          { colors: ["Gold","Silver","Space Gray","Rose Gold"], storages: ["16GB","32GB","64GB","128GB"] },
      "iPhone 6 Plus":      { colors: ["Gold","Silver","Space Gray"], storages: ["16GB","64GB","128GB"] },
      "iPhone 6":           { colors: ["Gold","Silver","Space Gray"], storages: ["16GB","64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "iPad": {
      "iPad Pro 13\" M4":    { colors: ["Silver","Space Black"], storages: ["256GB","512GB","1TB","2TB"] },
      "iPad Pro 11\" M4":    { colors: ["Silver","Space Black"], storages: ["256GB","512GB","1TB","2TB"] },
      "iPad Air M3 13\"":    { colors: ["Blue","Purple","Starlight","Space Gray"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPad Air M3 11\"":    { colors: ["Blue","Purple","Starlight","Space Gray"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPad Air M2 13\"":    { colors: ["Blue","Purple","Starlight","Space Gray"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPad Air M2 11\"":    { colors: ["Blue","Purple","Starlight","Space Gray"], storages: ["128GB","256GB","512GB","1TB"] },
      "iPad Pro 12.9\" M2":  { colors: ["Silver","Space Gray"], storages: ["128GB","256GB","512GB","1TB","2TB"] },
      "iPad Pro 11\" M2":    { colors: ["Silver","Space Gray"], storages: ["128GB","256GB","512GB","1TB","2TB"] },
      "iPad (10th Gen)":     { colors: ["Blue","Pink","Silver","Yellow"], storages: ["64GB","256GB"] },
      "iPad (9th Gen)":      { colors: ["Silver","Space Gray"], storages: ["64GB","256GB"] },
      "iPad mini 7":         { colors: ["Blue","Pink","Starlight","Purple"], storages: ["128GB","512GB"] },
      "iPad mini 6":         { colors: ["Purple","Starlight","Pink","Space Gray"], storages: ["64GB","256GB"] },
      "iPad Air 5":          { colors: ["Blue","Purple","Starlight","Pink","Space Gray"], storages: ["64GB","256GB"] },
      "iPad Air 4":          { colors: ["Space Gray","Silver","Rose Gold","Green","Sky Blue"], storages: ["64GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Apple Watch": {
      "Apple Watch Ultra 3":   { colors: ["Natural Titanium","Black Titanium"], storages: ["49mm"] },
      "Apple Watch Ultra 2":   { colors: ["Natural Titanium","Black Titanium"], storages: ["49mm"] },
      "Apple Watch Ultra":     { colors: ["Natural Titanium"], storages: ["49mm"] },
      "Apple Watch Series 10": { colors: ["Jet Black","Rose Gold","Silver","Titanium Natural","Titanium Black","Titanium Gold"], storages: ["42mm","46mm"] },
      "Apple Watch Series 9":  { colors: ["Midnight","Starlight","Silver","Pink","Red","Gold"], storages: ["41mm","45mm"] },
      "Apple Watch Series 8":  { colors: ["Midnight","Starlight","Silver","Red"], storages: ["41mm","45mm"] },
      "Apple Watch Series 7":  { colors: ["Midnight","Starlight","Green","Blue","Red"], storages: ["41mm","45mm"] },
      "Apple Watch Series 6":  { colors: ["Blue","Red","Space Gray","Silver","Gold","Gold Pink"], storages: ["40mm","44mm"] },
      "Apple Watch SE 2":      { colors: ["Midnight","Starlight","Silver"], storages: ["40mm","44mm"] },
      "Apple Watch SE":        { colors: ["Space Gray","Silver","Gold"], storages: ["40mm","44mm"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "MacBook": {
      "MacBook Air 15\" M4": { colors: ["Sky Blue","Stardust","Midnight","Starlight"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Air 13\" M4": { colors: ["Sky Blue","Stardust","Midnight","Starlight"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Air 15\" M3": { colors: ["Midnight","Starlight","Space Gray","Silver"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Air 13\" M3": { colors: ["Midnight","Starlight","Space Gray","Silver"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Air 13\" M2": { colors: ["Midnight","Starlight","Space Gray","Silver"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Air 13\" M1": { colors: ["Space Gray","Silver","Gold","Rose Gold"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Pro 16\" M4": { colors: ["Space Black","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 14\" M4": { colors: ["Space Black","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 16\" M3": { colors: ["Space Black","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 14\" M3": { colors: ["Space Black","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 16\" M2": { colors: ["Space Gray","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 14\" M2": { colors: ["Space Gray","Silver"], storages: ["512GB","1TB","2TB","4TB"] },
      "MacBook Pro 13\" M2": { colors: ["Space Gray","Silver"], storages: ["256GB","512GB","1TB","2TB"] },
      "MacBook Pro 13\" M1": { colors: ["Space Gray","Silver"], storages: ["256GB","512GB","1TB","2TB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "AirPods": {
      "AirPods 4 (ANC)":      { colors: ["White"], storages: [] },
      "AirPods 4":            { colors: ["White"], storages: [] },
      "AirPods 3rd Gen":      { colors: ["White"], storages: [] },
      "AirPods 2nd Gen":      { colors: ["White"], storages: [] },
      "AirPods Pro 2nd Gen":  { colors: ["White"], storages: [] },
      "AirPods Pro 1st Gen":  { colors: ["White"], storages: [] },
      "AirPods Max (2024)":   { colors: ["Midnight","Starlight","Blue","Purple","Orange"], storages: [] },
      "AirPods Max":          { colors: ["Space Gray","Silver","Green","Sky Blue","Pink"], storages: [] },
      [OTHER]: { colors: [], storages: [] },
    },
    "iMac": {
      "iMac 24\" M4": { colors: ["Silver","Blue","Green","Pink","Yellow","Orange","Purple"], storages: ["256GB","512GB","1TB","2TB"] },
      "iMac 24\" M3": { colors: ["Silver","Blue","Green","Pink","Yellow","Orange","Purple"], storages: ["256GB","512GB","1TB","2TB"] },
      "iMac 24\" M1": { colors: ["Silver","Blue","Green","Pink","Yellow","Orange","Purple"], storages: ["256GB","512GB","1TB","2TB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Samsung": {
    "Galaxy S": {
      "Galaxy S25 Ultra":  { colors: ["تيتانيوم أزرق فضي","تيتانيوم أسود","تيتانيوم أبيض","تيتانيوم رمادي"], storages: ["256GB","512GB","1TB"] },
      "Galaxy S25+":       { colors: ["أزرق جليدي","نعناعي","كحلي","ظل فضي"], storages: ["256GB","512GB"] },
      "Galaxy S25":        { colors: ["أزرق جليدي","نعناعي","كحلي","ظل فضي"], storages: ["128GB","256GB","512GB"] },
      "Galaxy S24 Ultra":  { colors: ["تيتانيوم أسود","تيتانيوم رمادي","تيتانيوم بنفسجي","تيتانيوم أصفر"], storages: ["256GB","512GB","1TB"] },
      "Galaxy S24+":       { colors: ["بنفسجي كوبالت","أخضر زمردي","أسود أونيكس","برتقالي رملي"], storages: ["256GB","512GB"] },
      "Galaxy S24":        { colors: ["بنفسجي كوبالت","أخضر زمردي","أسود أونيكس","رمادي رخامي"], storages: ["128GB","256GB","512GB"] },
      "Galaxy S24 FE":     { colors: ["أزرق","رمادي","أخضر","أصفر"], storages: ["128GB","256GB"] },
      "Galaxy S23 Ultra":  { colors: ["أسود فانتوم","كريم","أخضر","لافندر"], storages: ["256GB","512GB"] },
      "Galaxy S23+":       { colors: ["أسود فانتوم","كريم","أخضر","لافندر"], storages: ["256GB","512GB"] },
      "Galaxy S23":        { colors: ["أسود فانتوم","كريم","أخضر","لافندر"], storages: ["128GB","256GB","512GB"] },
      "Galaxy S23 FE":     { colors: ["جرافيت","أخضر","كريم","بنفسجي"], storages: ["128GB","256GB"] },
      "Galaxy S22 Ultra":  { colors: ["بورجندي","أخضر","أسود فانتوم","أبيض فانتوم"], storages: ["128GB","256GB","512GB","1TB"] },
      "Galaxy S22+":       { colors: ["أخضر","أسود فانتوم","أبيض فانتوم","بنفسجي"], storages: ["128GB","256GB"] },
      "Galaxy S22":        { colors: ["أخضر","أسود فانتوم","أبيض فانتوم","وردي ذهبي"], storages: ["128GB","256GB"] },
      "Galaxy S21 Ultra":  { colors: ["أسود فانتوم","فضي فانتوم","تيتانيوم","قهوة"], storages: ["128GB","256GB","512GB"] },
      "Galaxy S21+":       { colors: ["أسود فانتوم","فضي فانتوم","بنفسجي","ذهبي وردي"], storages: ["128GB","256GB"] },
      "Galaxy S21":        { colors: ["أسود فانتوم","رمادي فانتوم","أبيض فانتوم","بنفسجي","ذهبي وردي"], storages: ["128GB","256GB"] },
      "Galaxy S21 FE":     { colors: ["أبيض","أسود","أخضر","لافندر","وردي"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Galaxy A": {
      "Galaxy A55":  { colors: ["أزرق جليدي","ليلكي","كحلي"], storages: ["128GB","256GB"] },
      "Galaxy A54":  { colors: ["أبيض مذهل","أسود مذهل","أخضر مذهل","بنفسجي مذهل"], storages: ["128GB","256GB"] },
      "Galaxy A35":  { colors: ["أزرق جليدي","ليلكي","كحلي"], storages: ["128GB","256GB"] },
      "Galaxy A34":  { colors: ["لايم","فضي","بنفسجي","أسود"], storages: ["128GB","256GB"] },
      "Galaxy A25":  { colors: ["أسود مذهل","أزرق مذهل","أصفر مذهل"], storages: ["128GB","256GB"] },
      "Galaxy A24":  { colors: ["أسود","أخضر فاتح","وردي فاتح"], storages: ["128GB","256GB"] },
      "Galaxy A15":  { colors: ["أسود","أزرق","أصفر","أزرق فاتح"], storages: ["128GB"] },
      "Galaxy A14":  { colors: ["أسود","أخضر فاتح","فضي"], storages: ["64GB","128GB"] },
      "Galaxy A13":  { colors: ["أسود","أبيض","أزرق","وردي"], storages: ["32GB","64GB","128GB"] },
      "Galaxy A12":  { colors: ["أسود","أبيض","أزرق","أحمر"], storages: ["32GB","64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Galaxy Z": {
      "Galaxy Z Fold 6":  { colors: ["أزرق","وردي","ظل فضي","أبيض"], storages: ["256GB","512GB","1TB"] },
      "Galaxy Z Fold 5":  { colors: ["كريم","أيس نيلي","فانتوم أسود"], storages: ["256GB","512GB","1TB"] },
      "Galaxy Z Fold 4":  { colors: ["أخضر مطفي","بيج","فانتوم أسود","بورجندي"], storages: ["256GB","512GB","1TB"] },
      "Galaxy Z Flip 6":  { colors: ["أزرق","أصفر","فضي","نعناعي"], storages: ["256GB","512GB"] },
      "Galaxy Z Flip 5":  { colors: ["كريم","جرافيت","لافندر","نعناعي"], storages: ["256GB","512GB"] },
      "Galaxy Z Flip 4":  { colors: ["بنفسجي","أزرق","ذهبي","جرافيت","وردي ذهبي"], storages: ["128GB","256GB","512GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Galaxy Tab": {
      "Galaxy Tab S9 Ultra": { colors: ["بيج","جرافيت"], storages: ["128GB","256GB","512GB","1TB"] },
      "Galaxy Tab S9+":      { colors: ["بيج","جرافيت"], storages: ["128GB","256GB","512GB"] },
      "Galaxy Tab S9":       { colors: ["بيج","جرافيت"], storages: ["128GB","256GB"] },
      "Galaxy Tab S9 FE":    { colors: ["أخضر","لافندر","رمادي","أبيض"], storages: ["128GB","256GB"] },
      "Galaxy Tab S8 Ultra": { colors: ["جرافيت"], storages: ["128GB","256GB","512GB"] },
      "Galaxy Tab S8+":      { colors: ["فضي","جرافيت"], storages: ["128GB","256GB"] },
      "Galaxy Tab S8":       { colors: ["فضي","جرافيت","وردي ذهبي"], storages: ["128GB","256GB"] },
      "Galaxy Tab A8":       { colors: ["فضي","رمادي","وردي ذهبي"], storages: ["32GB","64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Xiaomi": {
    "Xiaomi": {
      "Xiaomi 14 Ultra":  { colors: ["أبيض","أسود","تيتانيوم"], storages: ["256GB","512GB","1TB"] },
      "Xiaomi 14 Pro":    { colors: ["أسود","أبيض","أخضر","بنفسجي"], storages: ["256GB","512GB","1TB"] },
      "Xiaomi 14":        { colors: ["أسود","أبيض","أخضر","أزرق"], storages: ["256GB","512GB"] },
      "Xiaomi 14T Pro":   { colors: ["أسود ألباين","أبيض ألباين","سماوي"], storages: ["256GB","512GB","1TB"] },
      "Xiaomi 14T":       { colors: ["أسود ألباين","أبيض ألباين","سماوي"], storages: ["256GB","512GB"] },
      "Xiaomi 13 Pro":    { colors: ["أسود سيراميك","أبيض سيراميك","أخضر زيتوني"], storages: ["256GB","512GB"] },
      "Xiaomi 13":        { colors: ["أسود","أبيض","أخضر"], storages: ["128GB","256GB"] },
      "Xiaomi 12 Pro":    { colors: ["رمادي","أزرق","بنفسجي","أبيض"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Redmi": {
      "Redmi Note 14 Pro+": { colors: ["أسود","أخضر","بنفسجي"], storages: ["256GB","512GB"] },
      "Redmi Note 14 Pro":  { colors: ["أسود","أخضر","بنفسجي"], storages: ["128GB","256GB"] },
      "Redmi Note 14":      { colors: ["أسود","أخضر","أزرق"], storages: ["128GB","256GB"] },
      "Redmi Note 13 Pro+": { colors: ["أسود","أبيض","أخضر","بنفسجي"], storages: ["256GB","512GB"] },
      "Redmi Note 13 Pro":  { colors: ["أسود","أبيض","أخضر","بنفسجي"], storages: ["128GB","256GB","512GB"] },
      "Redmi Note 13":      { colors: ["أسود","أخضر","أزرق","وردي"], storages: ["128GB","256GB"] },
      "Redmi Note 12 Pro":  { colors: ["أبيض","أسود","أزرق"], storages: ["128GB","256GB"] },
      "Redmi Note 12":      { colors: ["أبيض","أسود","أزرق","وردي"], storages: ["64GB","128GB","256GB"] },
      "Redmi 13C":          { colors: ["أسود","أخضر","أزرق"], storages: ["64GB","128GB"] },
      "Redmi 12":           { colors: ["أسود","أزرق","ذهبي","فضي"], storages: ["64GB","128GB","256GB"] },
      "Redmi 10C":          { colors: ["أسود","رمادي","أزرق","وردي"], storages: ["32GB","64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "POCO": {
      "POCO F6 Pro":  { colors: ["أسود","أبيض","رمادي"], storages: ["256GB","512GB","1TB"] },
      "POCO X6 Pro":  { colors: ["أسود","أبيض","أصفر"], storages: ["256GB","512GB"] },
      "POCO X5 Pro":  { colors: ["أسود","أصفر","أزرق"], storages: ["128GB","256GB"] },
      "POCO M6 Pro":  { colors: ["أسود","أبيض","بنفسجي"], storages: ["128GB","256GB","512GB"] },
      "POCO M5":      { colors: ["أسود","أصفر","أخضر"], storages: ["64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Huawei": {
    "سلسلة P": {
      "Huawei P60 Pro": { colors: ["أسود","رمادي لؤلؤي","أبيض"], storages: ["128GB","256GB","512GB"] },
      "Huawei P50 Pro": { colors: ["أسود","ذهبي","أبيض","أخضر"], storages: ["128GB","256GB","512GB"] },
      "Huawei P40 Pro": { colors: ["أسود","فضي جليدي","أخضر أعماق","سماوي"], storages: ["128GB","256GB","512GB"] },
      "Huawei P40":     { colors: ["أسود","فضي جليدي","أزرق"], storages: ["128GB","256GB"] },
      "Huawei P30 Pro": { colors: ["أسود","أبيض","تدرج الفجر","تدرج المحيط","أصفر"], storages: ["128GB","256GB","512GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "سلسلة Mate": {
      "Huawei Mate 50 Pro": { colors: ["أسود","أبيض","برتقالي"], storages: ["256GB","512GB"] },
      "Huawei Mate 40 Pro": { colors: ["أسود","فضي","ذهبي"], storages: ["128GB","256GB","512GB"] },
      "Huawei Mate 30 Pro": { colors: ["رمادي فضائي","أسود","بنفسجي فضائي","أخضر زمردي"], storages: ["128GB","256GB","512GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "سلسلة Nova": {
      "Huawei Nova 11": { colors: ["أسود","أخضر","ذهبي"], storages: ["128GB","256GB"] },
      "Huawei Nova 9":  { colors: ["أسود","أبيض","أزرق"], storages: ["128GB","256GB"] },
      "Huawei Nova 7":  { colors: ["أسود","فضي","أزرق سماوي","وردي"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "MatePad": {
      "Huawei MatePad Pro 13.2\"": { colors: ["أسود","فضي"], storages: ["128GB","256GB","512GB"] },
      "Huawei MatePad 11\"":       { colors: ["أبيض","رمادي","أخضر"], storages: ["64GB","128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "OPPO": {
    "Reno": {
      "OPPO Reno 12 Pro": { colors: ["بني ناعم","أخضر ناعم","رمادي"], storages: ["256GB","512GB"] },
      "OPPO Reno 11":     { colors: ["أسود","أخضر","وردي"], storages: ["128GB","256GB"] },
      "OPPO Reno 10 Pro": { colors: ["أبيض لامع","رمادي","بنفسجي"], storages: ["256GB"] },
      "OPPO Reno 10":     { colors: ["أبيض لامع","رمادي","بنفسجي"], storages: ["128GB","256GB"] },
      "OPPO Reno 8":      { colors: ["أسود لامع","أخضر لامع","أبيض"], storages: ["128GB","256GB"] },
      "OPPO Reno 7":      { colors: ["أسود","أزرق","ذهبي","وردي"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Find X": {
      "OPPO Find X7 Pro": { colors: ["أسود","بني مرمري","أخضر فارسي"], storages: ["256GB","512GB","1TB"] },
      "OPPO Find X6 Pro": { colors: ["أسود","بني","أبيض"], storages: ["256GB","512GB"] },
      "OPPO Find X5 Pro": { colors: ["أسود","أبيض"], storages: ["256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "A Series": {
      "OPPO A98": { colors: ["أسود","ذهبي","أزرق"], storages: ["128GB","256GB"] },
      "OPPO A78": { colors: ["أسود","أخضر","وردي"], storages: ["128GB"] },
      "OPPO A58": { colors: ["أسود","أخضر"], storages: ["128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "OnePlus": {
    "الرئيسية": {
      "OnePlus 12":     { colors: ["أسود سيليكاي","أخضر زمردي"], storages: ["256GB","512GB"] },
      "OnePlus 12R":    { colors: ["أسود","أخضر"], storages: ["128GB","256GB"] },
      "OnePlus 11":     { colors: ["أخضر زمردي","أسود تيتانيوم"], storages: ["128GB","256GB"] },
      "OnePlus 10 Pro": { colors: ["أسود ألكانتارا","أسود فولكانو","أخضر إمرالد"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Nord": {
      "OnePlus Nord 4":    { colors: ["أسود","أخضر","فضي","برتقالي"], storages: ["128GB","256GB","512GB"] },
      "OnePlus Nord CE 4": { colors: ["أسود","فضي رمادي","أصفر"], storages: ["128GB","256GB"] },
      "OnePlus Nord 3":    { colors: ["أخضر دودج","رمادي تمبست"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "realme": {
    "GT": {
      "realme GT 6":     { colors: ["أسود","أبيض"], storages: ["256GB","512GB","1TB"] },
      "realme GT 5 Pro": { colors: ["أسود","أبيض","أزرق","برتقالي"], storages: ["256GB","512GB","1TB"] },
      "realme GT 2 Pro": { colors: ["أبيض ورقي","أسود ورقي","أزرق ستيل"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "C Series": {
      "realme C67": { colors: ["أسود","أخضر","أزرق"], storages: ["128GB","256GB"] },
      "realme C55": { colors: ["أسود","أخضر","أبيض"], storages: ["64GB","128GB","256GB"] },
      "realme C35": { colors: ["أسود","أبيض","أخضر"], storages: ["64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Vivo": {
    "X Series": {
      "Vivo X100 Pro": { colors: ["أسود","أبيض","برتقالي"], storages: ["256GB","512GB","1TB"] },
      "Vivo X90 Pro":  { colors: ["أسود","أحمر أنتيك","أبيض"], storages: ["256GB","512GB"] },
      "Vivo X80 Pro":  { colors: ["أسود","أبيض"], storages: ["256GB","512GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "V Series": {
      "Vivo V30 Pro": { colors: ["أسود","ذهبي","وردي"], storages: ["256GB","512GB"] },
      "Vivo V27":     { colors: ["أسود الكون","أخضر لمس الأمطار","وردي"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Y Series": {
      "Vivo Y38": { colors: ["أسود","أخضر","ذهبي"], storages: ["128GB","256GB"] },
      "Vivo Y36": { colors: ["أسود","أخضر","ذهبي"], storages: ["128GB"] },
      "Vivo Y35": { colors: ["أسود","ذهبي","أبيض"], storages: ["128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Honor": {
    "Magic": {
      "Honor Magic 6 Pro": { colors: ["أسود","أخضر","برتقالي"], storages: ["256GB","512GB","1TB"] },
      "Honor Magic 5 Pro": { colors: ["أسود","أخضر","أزرق سماوي"], storages: ["256GB","512GB"] },
      "Honor Magic 4 Pro": { colors: ["أسود","أخضر","ذهبي"], storages: ["256GB","512GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "الرئيسية": {
      "Honor 90 Pro": { colors: ["أسود","أخضر","وردي"], storages: ["256GB","512GB"] },
      "Honor 90":     { colors: ["أسود","أخضر","وردي","فضي"], storages: ["256GB","512GB"] },
      "Honor 70":     { colors: ["أسود","فضي","أخضر"], storages: ["128GB","256GB"] },
      "Honor X9a":    { colors: ["أسود","أخضر","فضي"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Tecno": {
    "CAMON": {
      "Tecno CAMON 30 Pro": { colors: ["أسود","أخضر","أبيض"], storages: ["256GB","512GB"] },
      "Tecno CAMON 20 Pro": { colors: ["أسود","أخضر","أبيض"], storages: ["256GB"] },
      "Tecno CAMON 19 Pro": { colors: ["أسود","أبيض","أخضر"], storages: ["256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "SPARK": {
      "Tecno SPARK 20 Pro": { colors: ["أسود","أبيض","أزرق"], storages: ["128GB","256GB"] },
      "Tecno SPARK 10 Pro": { colors: ["أسود","أبيض","أزرق"], storages: ["128GB","256GB"] },
      "Tecno SPARK 20":     { colors: ["أسود","أبيض","أزرق","أخضر"], storages: ["64GB","128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "Phantom": {
      "Tecno Phantom X2 Pro": { colors: ["مارتيان ستينهيم","ستيلث بلاك"], storages: ["256GB","512GB"] },
      "Tecno Phantom X2":     { colors: ["مارتيان ستينهيم","ستيلث بلاك"], storages: ["256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Infinix": {
    "NOTE": {
      "Infinix NOTE 40 Pro": { colors: ["أسود","أخضر","رمادي"], storages: ["256GB","512GB"] },
      "Infinix NOTE 30":     { colors: ["أسود","أخضر","رمادي","أبيض"], storages: ["128GB","256GB"] },
      "Infinix NOTE 12":     { colors: ["أسود","أزرق","أبيض"], storages: ["128GB","256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "HOT": {
      "Infinix HOT 40 Pro": { colors: ["أسود","أبيض","أخضر","أحمر"], storages: ["128GB","256GB"] },
      "Infinix HOT 30":     { colors: ["أسود","أبيض","أخضر","برتقالي"], storages: ["64GB","128GB","256GB"] },
      "Infinix HOT 20":     { colors: ["أسود","أبيض","أخضر","ذهبي"], storages: ["64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
    "ZERO": {
      "Infinix ZERO 30 5G": { colors: ["أسود","أخضر","ذهبي"], storages: ["256GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
  "Nokia": {
    "الرئيسية": {
      "Nokia G42":  { colors: ["بنفسجي مطفي","رمادي","أخضر"], storages: ["128GB","256GB"] },
      "Nokia X30":  { colors: ["أزرق جليدي","رمادي أنثراسايت"], storages: ["128GB","256GB"] },
      "Nokia G21":  { colors: ["أزرق نورديك","رمادي نورديك"], storages: ["64GB","128GB"] },
      "Nokia C32":  { colors: ["أسود","أخضر","أبيض"], storages: ["64GB","128GB"] },
      [OTHER]: { colors: [], storages: [] },
    },
  },
};

export const BRANDS = [...Object.keys(CATALOG), OTHER];
export const DEFAULT_STORAGES = ["16GB","32GB","64GB","128GB","256GB","512GB","1TB"];
export const DEFAULT_COLORS   = ["أسود","أبيض","فضي","رمادي","ذهبي","أزرق","أحمر","أخضر","بنفسجي","وردي","بيج","برتقالي","أصفر"];

export const REPAIR_CATALOG: Record<string, Record<string, string[]>> = {
  "Apple": {
    "iPhone": [
      "iPhone 6","iPhone 6s","iPhone 6s Plus","iPhone SE (الجيل الأول)",
      "iPhone 7","iPhone 7 Plus","iPhone 8","iPhone 8 Plus","iPhone X",
      "iPhone XS","iPhone XS Max","iPhone XR",
      "iPhone 11","iPhone 11 Pro","iPhone 11 Pro Max",
      "iPhone SE (الجيل الثاني)","iPhone 12","iPhone 12 mini",
      "iPhone 12 Pro","iPhone 12 Pro Max",
      "iPhone 13","iPhone 13 mini","iPhone 13 Pro","iPhone 13 Pro Max",
      "iPhone SE (الجيل الثالث)","iPhone 14","iPhone 14 Plus","iPhone 14 Pro","iPhone 14 Pro Max",
      "iPhone 15","iPhone 15 Plus","iPhone 15 Pro","iPhone 15 Pro Max",
      "iPhone 16","iPhone 16 Plus","iPhone 16 Pro","iPhone 16 Pro Max",
    ],
    "iPad": [
      "iPad mini 4","iPad mini 5","iPad mini 6","iPad mini 7",
      "iPad Air 3","iPad Air 4","iPad Air 5","iPad Air M2",
      "iPad (الجيل السابع)","iPad (الجيل الثامن)","iPad (الجيل التاسع)","iPad (الجيل العاشر)",
      "iPad Pro 11\" (الجيل الأول)","iPad Pro 11\" (الجيل الثاني)","iPad Pro 11\" (الجيل الثالث)","iPad Pro 11\" M4",
      "iPad Pro 12.9\" (الجيل الثالث)","iPad Pro 12.9\" (الجيل الرابع)","iPad Pro 12.9\" (الجيل الخامس)","iPad Pro 12.9\" M2",
      "iPad Pro 13\" M4",
    ],
    "Apple Watch": [
      "Apple Watch Series 4","Apple Watch Series 5","Apple Watch SE (الجيل الأول)",
      "Apple Watch Series 6","Apple Watch Series 7","Apple Watch Series 8",
      "Apple Watch SE (الجيل الثاني)","Apple Watch Ultra","Apple Watch Series 9","Apple Watch Ultra 2",
    ],
    "AirPods": [
      "AirPods (الجيل الثاني)","AirPods (الجيل الثالث)",
      "AirPods Pro (الجيل الأول)","AirPods Pro (الجيل الثاني)","AirPods Max",
    ],
    "Mac": [
      "MacBook Air M1","MacBook Air M2","MacBook Air M3",
      "MacBook Pro 13\" M1","MacBook Pro 13\" M2",
      "MacBook Pro 14\" M1 Pro","MacBook Pro 14\" M2 Pro","MacBook Pro 14\" M3 Pro",
      "MacBook Pro 16\" M1 Pro","MacBook Pro 16\" M2 Pro","MacBook Pro 16\" M3 Pro",
      "iMac M1","iMac M3",
    ],
  },
  "Samsung": {
    "Galaxy S": [
      "Galaxy S20","Galaxy S20+","Galaxy S20 Ultra","Galaxy S20 FE",
      "Galaxy S21","Galaxy S21+","Galaxy S21 Ultra","Galaxy S21 FE",
      "Galaxy S22","Galaxy S22+","Galaxy S22 Ultra",
      "Galaxy S23","Galaxy S23+","Galaxy S23 Ultra","Galaxy S23 FE",
      "Galaxy S24","Galaxy S24+","Galaxy S24 Ultra","Galaxy S24 FE",
      "Galaxy S25","Galaxy S25+","Galaxy S25 Ultra",
    ],
    "Galaxy A": [
      "Galaxy A03s","Galaxy A04s","Galaxy A05s",
      "Galaxy A12","Galaxy A13","Galaxy A14","Galaxy A15","Galaxy A16",
      "Galaxy A22","Galaxy A23","Galaxy A24","Galaxy A25","Galaxy A26",
      "Galaxy A32","Galaxy A33","Galaxy A34","Galaxy A35","Galaxy A36",
      "Galaxy A52","Galaxy A52s","Galaxy A53","Galaxy A54","Galaxy A55","Galaxy A56",
      "Galaxy A72","Galaxy A73","Galaxy A74",
    ],
    "Galaxy M": [
      "Galaxy M12","Galaxy M13","Galaxy M14","Galaxy M15",
      "Galaxy M23","Galaxy M33","Galaxy M34","Galaxy M35",
      "Galaxy M53","Galaxy M54","Galaxy M55",
    ],
    "Galaxy Z": [
      "Galaxy Z Fold 3","Galaxy Z Fold 4","Galaxy Z Fold 5","Galaxy Z Fold 6",
      "Galaxy Z Flip 3","Galaxy Z Flip 4","Galaxy Z Flip 5","Galaxy Z Flip 6",
    ],
    "Galaxy Tab": [
      "Galaxy Tab A7","Galaxy Tab A7 Lite","Galaxy Tab A8",
      "Galaxy Tab S6 Lite","Galaxy Tab S7","Galaxy Tab S7+","Galaxy Tab S7 FE",
      "Galaxy Tab S8","Galaxy Tab S8+","Galaxy Tab S8 Ultra",
      "Galaxy Tab S9","Galaxy Tab S9+","Galaxy Tab S9 Ultra","Galaxy Tab S9 FE",
    ],
  },
  "Xiaomi": {
    "Redmi": [
      "Redmi 9","Redmi 9A","Redmi 9C","Redmi 10","Redmi 10A","Redmi 10C",
      "Redmi 12","Redmi 12C","Redmi 13","Redmi 13C",
      "Redmi Note 10","Redmi Note 10 Pro","Redmi Note 10S",
      "Redmi Note 11","Redmi Note 11 Pro","Redmi Note 11S",
      "Redmi Note 12","Redmi Note 12 Pro","Redmi Note 12S",
      "Redmi Note 13","Redmi Note 13 Pro","Redmi Note 13 Pro+",
    ],
    "Xiaomi": [
      "Xiaomi 12","Xiaomi 12 Pro","Xiaomi 12 Lite",
      "Xiaomi 13","Xiaomi 13 Pro","Xiaomi 13 Lite",
      "Xiaomi 14","Xiaomi 14 Pro","Xiaomi 14 Ultra",
    ],
    "POCO": [
      "POCO X3 NFC","POCO X3 Pro","POCO X4 Pro","POCO X5 Pro","POCO X6 Pro",
      "POCO M4 Pro","POCO M5","POCO M5s","POCO M6 Pro",
      "POCO F3","POCO F4","POCO F5","POCO F6",
    ],
    "Xiaomi Pad": [
      "Xiaomi Pad 5","Xiaomi Pad 5 Pro","Xiaomi Pad 6","Xiaomi Pad 6 Pro",
    ],
  },
  "Huawei": {
    "P Series": [
      "P30","P30 Pro","P40","P40 Pro","P40 Lite",
      "P50","P50 Pro","P50 Pocket","P60","P60 Pro","P60 Art",
    ],
    "Mate Series": [
      "Mate 20","Mate 20 Pro","Mate 30","Mate 30 Pro",
      "Mate 40","Mate 40 Pro","Mate 50","Mate 50 Pro","Mate 60 Pro",
    ],
    "Nova Series": [
      "Nova 7i","Nova 8","Nova 8i","Nova 9","Nova 9 Pro",
      "Nova 10","Nova 10 Pro","Nova 11","Nova 11 Pro",
    ],
    "Y Series": [
      "Y6p","Y7a","Y8p","Y8s","Y9a","Y90",
    ],
    "MatePad": [
      "MatePad 10.4","MatePad 11","MatePad Pro 11","MatePad Pro 12.6",
    ],
  },
  "Oppo": {
    "A Series": [
      "A15","A16","A17","A18","A54","A55","A57","A57s","A58","A74","A77","A78","A79","A96","A98",
    ],
    "Reno": [
      "Reno 6","Reno 6 Pro","Reno 7","Reno 7 Pro","Reno 8","Reno 8 Pro",
      "Reno 10","Reno 10 Pro","Reno 11","Reno 11 Pro","Reno 12 Pro",
    ],
    "Find X": [
      "Find X3 Pro","Find X5 Pro","Find X6 Pro","Find X7 Ultra",
    ],
    "F Series": [
      "F19","F19 Pro","F21 Pro","F23","F25 Pro",
    ],
  },
  "Vivo": {
    "Y Series": [
      "Y15s","Y16","Y17s","Y21","Y21s","Y22","Y22s","Y27","Y27s","Y28",
      "Y33s","Y35","Y36","Y55","Y55s","Y72","Y73","Y75","Y76","Y78",
    ],
    "V Series": [
      "V21","V21e","V23","V23e","V25","V25 Pro","V27","V27 Pro","V29","V29 Pro","V40",
    ],
    "X Series": [
      "X80","X80 Pro","X90","X90 Pro","X100","X100 Pro",
    ],
  },
  "Realme": {
    "C Series": [
      "C21","C21Y","C25","C25s","C25Y","C30","C31","C33","C35","C55","C67",
    ],
    "Number Series": [
      "Realme 9","Realme 9i","Realme 9 Pro","Realme 9 Pro+",
      "Realme 10","Realme 10 Pro","Realme 10 Pro+",
      "Realme 11","Realme 11 Pro","Realme 11 Pro+",
      "Realme 12 Pro","Realme 12 Pro+",
    ],
    "GT Series": [
      "Realme GT Neo 2","Realme GT Neo 3","Realme GT Neo 5","Realme GT 5",
    ],
    "Narzo": [
      "Narzo 50","Narzo 50A","Narzo 60","Narzo 70",
    ],
  },
  "Nokia": {
    "G Series": ["Nokia G10","Nokia G20","Nokia G21","Nokia G22","Nokia G42"],
    "C Series": ["Nokia C20","Nokia C21","Nokia C30","Nokia C31","Nokia C32"],
    "X Series": ["Nokia X10","Nokia X20","Nokia X30"],
  },
  "OnePlus": {
    "OnePlus": [
      "OnePlus 9","OnePlus 9 Pro","OnePlus 10 Pro","OnePlus 10T",
      "OnePlus 11","OnePlus 11R","OnePlus 12","OnePlus 12R",
    ],
    "Nord": [
      "Nord 2","Nord 2T","Nord 3","Nord CE 2","Nord CE 3","Nord CE 4",
    ],
  },
  "أخرى": {
    "جهاز آخر": [],
  },
};
