import type { AuthUser } from "@/contexts/auth";

/* ══ ROLE_DEFAULTS ═══════════════════════════════════════════════════════
   Explicit defaults per role. User-level overrides always win first.
   ════════════════════════════════════════════════════════════════════════ */
const ROLE_DEFAULTS: Record<string, Record<string, boolean>> = {

  /* ── مدير النظام: كل الصلاحيات ──────────────────────────────────── */
  admin: {
    // وصول الصفحات
    can_access_dashboard: true, can_access_pos: true, can_access_sales: true,
    can_access_purchases: true, can_access_products: true, can_access_inventory: true,
    can_access_customers: true, can_access_returns: true, can_access_devices: true,
    can_access_repairs: true, can_access_warranty: true, can_access_scrap_inventory: true,
    can_access_bad_debts: true, can_access_income: true, can_access_expenses: true,
    can_access_treasury: true, can_access_vouchers: true, can_access_reports: true,
    can_access_accounts: true, can_access_journal_entries: true, can_access_fixed_assets: true,
    can_access_accruals: true, can_access_bank_reconciliation: true, can_access_budgets: true,
    can_access_cost_centers: true, can_access_fiscal_years: true, can_access_audit_log: true,
    can_access_branches: true, can_access_employees: true, can_access_attendance: true,
    can_access_settings: true, can_access_transfers: true,
    // المبيعات
    can_view_sales: true, can_create_sale: true, can_cash_sale: true,
    can_partial_sale: true, can_credit_sale: true, can_cancel_sale: true,
    can_return_sale: true, can_edit_price: true,
    can_view_returns: true, can_manage_returns: true,
    // المخزون والمشتريات
    can_view_products: true, can_manage_products: true,
    can_view_inventory: true, can_adjust_inventory: true,
    can_view_purchases: true, can_create_purchase: true, can_cancel_purchase: true,
    can_view_transfers: true, can_manage_transfers: true,
    // العملاء
    can_view_customers: true, can_manage_customers: true,
    can_view_bad_debts: true, can_manage_bad_debts: true,
    // المالية
    can_view_treasury: true, can_view_expenses: true, can_add_expense: true,
    can_view_income: true, can_add_income: true,
    can_view_vouchers: true, can_manage_vouchers: true,
    can_add_receipt_voucher: true, can_add_payment_voucher: true, can_close_shift: true,
    // التقارير
    can_view_reports: true,
    // الصيانة
    can_view_repairs: true, can_manage_repairs: true,
    can_view_devices: true, can_manage_devices: true,
    can_view_warranty: true, can_manage_warranty: true,
    can_view_scrap_inventory: true, can_manage_scrap_inventory: true,
    // الموارد البشرية
    can_view_employees: true, can_manage_employees: true, can_view_employee_salary: true,
    can_view_payroll: true, can_manage_payroll: true, can_approve_payroll: true,
    can_view_attendance: true, can_manage_attendance: true,
    can_view_leaves: true, can_manage_leaves: true,
    // المحاسبة
    can_view_accounts: true, can_manage_accounts: true,
    can_view_journal_entries: true, can_manage_journal_entries: true,
    can_view_fixed_assets: true, can_manage_fixed_assets: true,
    can_view_accruals: true, can_manage_accruals: true,
    can_view_bank_reconciliation: true, can_manage_bank_reconciliation: true,
    can_view_budgets: true, can_manage_budgets: true,
    can_view_cost_centers: true, can_manage_cost_centers: true,
    can_view_fiscal_years: true, can_manage_fiscal_years: true,
    // النظام
    can_view_branches: true, can_manage_branches: true,
    can_manage_users: true, can_manage_settings: true, can_view_audit_log: true,
  },

  /* ── مشرف ───────────────────────────────────────────────────────── */
  manager: {
    can_access_dashboard: true,  can_access_pos: true, can_access_sales: true,
    can_access_purchases: true,  can_access_products: true, can_access_inventory: true,
    can_access_customers: true,  can_access_returns: true, can_access_devices: true,
    can_access_repairs: true,    can_access_warranty: true, can_access_scrap_inventory: true,
    can_access_bad_debts: true,  can_access_income: true, can_access_expenses: true,
    can_access_treasury: true,   can_access_vouchers: true, can_access_reports: true,
    can_access_budgets: true,    can_access_branches: true, can_access_employees: true,
    can_access_attendance: true, can_access_transfers: true,
    can_access_accounts: false,  can_access_journal_entries: false, can_access_fixed_assets: false,
    can_access_accruals: false,  can_access_bank_reconciliation: false,
    can_access_cost_centers: false, can_access_fiscal_years: false,
    can_access_audit_log: false, can_access_settings: false,
    can_view_sales: true, can_create_sale: true, can_cash_sale: true,
    can_partial_sale: true, can_credit_sale: true, can_cancel_sale: true,
    can_return_sale: true, can_edit_price: true,
    can_view_returns: true, can_manage_returns: true,
    can_view_products: true,   can_manage_products: true,
    can_view_inventory: true,  can_adjust_inventory: true,
    can_view_purchases: true,  can_create_purchase: true, can_cancel_purchase: true,
    can_view_transfers: true,  can_manage_transfers: true,
    can_view_customers: true,  can_manage_customers: true,
    can_view_bad_debts: true,  can_manage_bad_debts: true,
    can_view_treasury: true,       can_view_expenses: true,    can_add_expense: true,
    can_view_income: true,         can_add_income: true,
    can_view_vouchers: true,       can_manage_vouchers: true,
    can_add_receipt_voucher: true, can_add_payment_voucher: true, can_close_shift: true,
    can_view_reports: true,
    can_view_repairs: true,   can_manage_repairs: true,
    can_view_devices: true,   can_manage_devices: true,
    can_view_warranty: true,  can_manage_warranty: true,
    can_view_scrap_inventory: true, can_manage_scrap_inventory: true,
    can_view_employees: true,      can_manage_employees: true, can_view_employee_salary: true,
    can_view_payroll: true,        can_manage_payroll: false,  can_approve_payroll: false,
    can_view_attendance: true,     can_manage_attendance: true,
    can_view_leaves: true,         can_manage_leaves: true,
    can_view_budgets: true,        can_manage_budgets: true,
    can_view_branches: true,       can_manage_branches: false,
    can_manage_users: false, can_manage_settings: false, can_view_audit_log: false,
    can_view_accounts: false, can_manage_accounts: false,
    can_view_journal_entries: false, can_manage_journal_entries: false,
    can_view_fixed_assets: false,    can_manage_fixed_assets: false,
    can_view_accruals: false,        can_manage_accruals: false,
    can_view_bank_reconciliation: false, can_manage_bank_reconciliation: false,
    can_view_cost_centers: false,    can_manage_cost_centers: false,
    can_view_fiscal_years: false,    can_manage_fiscal_years: false,
  },

  /* ── مندوب مبيعات ───────────────────────────────────────────────── */
  salesperson: {
    can_access_dashboard: true, can_access_sales: true, can_access_pos: true,
    can_access_products: true,  can_access_customers: true, can_access_treasury: true,
    can_access_returns: false, can_access_inventory: false, can_access_purchases: false,
    can_access_transfers: false, can_access_bad_debts: false, can_access_expenses: false,
    can_access_income: false, can_access_vouchers: false, can_access_reports: false,
    can_access_repairs: false, can_access_devices: false, can_access_warranty: false,
    can_access_scrap_inventory: false, can_access_employees: false, can_access_attendance: false,
    can_access_budgets: false, can_access_branches: false, can_access_settings: false,
    can_access_audit_log: false, can_access_accounts: false, can_access_journal_entries: false,
    can_access_fixed_assets: false, can_access_accruals: false,
    can_access_bank_reconciliation: false, can_access_cost_centers: false,
    can_access_fiscal_years: false,
    can_view_sales: true, can_create_sale: true, can_cash_sale: true,
    can_partial_sale: true, can_credit_sale: true,
    can_return_sale: false, can_cancel_sale: false, can_edit_price: false,
    can_view_returns: false, can_manage_returns: false,
    can_view_products: true,   can_manage_products: false,
    can_view_inventory: false, can_adjust_inventory: false,
    can_view_purchases: false, can_create_purchase: false, can_cancel_purchase: false,
    can_view_transfers: false, can_manage_transfers: false,
    can_view_customers: true,  can_manage_customers: false,
    can_view_bad_debts: false, can_manage_bad_debts: false,
    can_view_treasury: true,
    can_view_expenses: false, can_add_expense: false,
    can_view_income: false,   can_add_income: false,
    can_view_vouchers: false, can_manage_vouchers: false,
    can_add_receipt_voucher: false, can_add_payment_voucher: false, can_close_shift: false,
    can_view_reports: false,
    can_view_repairs: false, can_manage_repairs: false,
    can_view_devices: false, can_manage_devices: false,
    can_view_warranty: false, can_manage_warranty: false,
    can_view_scrap_inventory: false, can_manage_scrap_inventory: false,
    can_view_employees: false, can_manage_employees: false, can_view_employee_salary: false,
    can_view_payroll: false,   can_manage_payroll: false, can_approve_payroll: false,
    can_view_attendance: false, can_manage_attendance: false,
    can_view_leaves: false,    can_manage_leaves: false,
    can_view_budgets: false,   can_manage_budgets: false,
    can_view_branches: false,  can_manage_branches: false,
    can_manage_users: false,   can_manage_settings: false, can_view_audit_log: false,
    can_view_accounts: false,  can_manage_accounts: false,
    can_view_journal_entries: false, can_manage_journal_entries: false,
    can_view_fixed_assets: false,    can_manage_fixed_assets: false,
    can_view_accruals: false,        can_manage_accruals: false,
    can_view_bank_reconciliation: false, can_manage_bank_reconciliation: false,
    can_view_cost_centers: false,    can_manage_cost_centers: false,
    can_view_fiscal_years: false,    can_manage_fiscal_years: false,
  },

  /* ── كاشير ──────────────────────────────────────────────────────── */
  cashier: {
    can_access_dashboard: true,  can_access_sales: true, can_access_pos: true,
    can_access_products: true,   can_access_customers: true, can_access_treasury: true,
    can_access_expenses: true,   can_access_repairs: true, can_access_devices: true,
    can_access_warranty: true,
    can_access_returns: false,   can_access_inventory: false, can_access_purchases: false,
    can_access_transfers: false, can_access_bad_debts: false, can_access_income: false,
    can_access_vouchers: false,  can_access_reports: false, can_access_scrap_inventory: false,
    can_access_employees: false, can_access_attendance: false, can_access_budgets: false,
    can_access_branches: false,  can_access_settings: false, can_access_audit_log: false,
    can_access_accounts: false,  can_access_journal_entries: false, can_access_fixed_assets: false,
    can_access_accruals: false,  can_access_bank_reconciliation: false,
    can_access_cost_centers: false, can_access_fiscal_years: false,
    can_view_sales: true, can_create_sale: true, can_cash_sale: true,
    can_partial_sale: false, can_credit_sale: false,
    can_return_sale: false, can_cancel_sale: false, can_edit_price: false,
    can_view_returns: false, can_manage_returns: false,
    can_view_products: true,   can_manage_products: false,
    can_view_inventory: false, can_adjust_inventory: false,
    can_view_purchases: false, can_create_purchase: false, can_cancel_purchase: false,
    can_view_transfers: false, can_manage_transfers: false,
    can_view_customers: true,  can_manage_customers: false,
    can_view_bad_debts: false, can_manage_bad_debts: false,
    can_view_treasury: true,
    can_view_expenses: true,  can_add_expense: true,
    can_view_income: false,   can_add_income: false,
    can_view_vouchers: false, can_manage_vouchers: false,
    can_add_receipt_voucher: false, can_add_payment_voucher: false, can_close_shift: true,
    can_view_reports: false,
    can_view_repairs: true,   can_manage_repairs: false,
    can_view_devices: true,   can_manage_devices: false,
    can_view_warranty: true,  can_manage_warranty: false,
    can_view_scrap_inventory: false, can_manage_scrap_inventory: false,
    can_view_employees: false, can_manage_employees: false, can_view_employee_salary: false,
    can_view_payroll: false,   can_manage_payroll: false, can_approve_payroll: false,
    can_view_attendance: false, can_manage_attendance: false,
    can_view_leaves: false,    can_manage_leaves: false,
    can_view_budgets: false,   can_manage_budgets: false,
    can_view_branches: false,  can_manage_branches: false,
    can_manage_users: false,   can_manage_settings: false, can_view_audit_log: false,
    can_view_accounts: false,  can_manage_accounts: false,
    can_view_journal_entries: false, can_manage_journal_entries: false,
    can_view_fixed_assets: false,    can_manage_fixed_assets: false,
    can_view_accruals: false,        can_manage_accruals: false,
    can_view_bank_reconciliation: false, can_manage_bank_reconciliation: false,
    can_view_cost_centers: false,    can_manage_cost_centers: false,
    can_view_fiscal_years: false,    can_manage_fiscal_years: false,
  },

  /* ── موظف (بوابة ذاتية) ─────────────────────────────────────────── */
  employee: {
    can_access_employees: true, can_access_attendance: true,
    can_access_dashboard: false, can_access_pos: false, can_access_sales: false,
    can_access_purchases: false, can_access_products: false, can_access_inventory: false,
    can_access_customers: false, can_access_returns: false, can_access_devices: false,
    can_access_repairs: false, can_access_warranty: false, can_access_scrap_inventory: false,
    can_access_bad_debts: false, can_access_income: false, can_access_expenses: false,
    can_access_treasury: false, can_access_vouchers: false, can_access_reports: false,
    can_access_accounts: false, can_access_journal_entries: false, can_access_fixed_assets: false,
    can_access_accruals: false, can_access_bank_reconciliation: false, can_access_budgets: false,
    can_access_cost_centers: false, can_access_fiscal_years: false, can_access_audit_log: false,
    can_access_branches: false, can_access_settings: false, can_access_transfers: false,
    can_view_employees: true, can_view_employee_salary: true,
    can_view_attendance: true, can_view_leaves: true,
    can_view_payroll: false,
    can_manage_employees: false, can_manage_attendance: false, can_manage_leaves: false,
    can_manage_payroll: false, can_approve_payroll: false,
    can_view_sales: false, can_create_sale: false, can_cash_sale: false,
    can_partial_sale: false, can_credit_sale: false, can_cancel_sale: false,
    can_return_sale: false, can_edit_price: false,
    can_view_returns: false, can_manage_returns: false,
    can_view_products: false, can_manage_products: false,
    can_view_inventory: false, can_adjust_inventory: false,
    can_view_purchases: false, can_create_purchase: false, can_cancel_purchase: false,
    can_view_transfers: false, can_manage_transfers: false,
    can_view_customers: false, can_manage_customers: false,
    can_view_bad_debts: false, can_manage_bad_debts: false,
    can_view_treasury: false, can_view_expenses: false, can_add_expense: false,
    can_view_income: false, can_add_income: false,
    can_view_vouchers: false, can_manage_vouchers: false,
    can_add_receipt_voucher: false, can_add_payment_voucher: false, can_close_shift: false,
    can_view_reports: false,
    can_view_repairs: false, can_manage_repairs: false,
    can_view_devices: false, can_manage_devices: false,
    can_view_warranty: false, can_manage_warranty: false,
    can_view_scrap_inventory: false, can_manage_scrap_inventory: false,
    can_view_budgets: false, can_manage_budgets: false,
    can_view_branches: false, can_manage_branches: false,
    can_manage_users: false, can_manage_settings: false, can_view_audit_log: false,
    can_view_accounts: false, can_manage_accounts: false,
    can_view_journal_entries: false, can_manage_journal_entries: false,
    can_view_fixed_assets: false,    can_manage_fixed_assets: false,
    can_view_accruals: false,        can_manage_accruals: false,
    can_view_bank_reconciliation: false, can_manage_bank_reconciliation: false,
    can_view_cost_centers: false,    can_manage_cost_centers: false,
    can_view_fiscal_years: false,    can_manage_fiscal_years: false,
  },
};

export function hasPermission(
  user: AuthUser | null | undefined,
  permission: string,
): boolean {
  if (!user) return false;

  const perms = user.permissions ?? {};

  // Explicit user-level override always wins
  if (perms[permission] === true)  return true;
  if (perms[permission] === false) return false;

  // Fall back to role defaults
  const roleDefaults = ROLE_DEFAULTS[user.role] ?? {};
  if (roleDefaults[permission] === true)  return true;
  if (roleDefaults[permission] === false) return false;

  // Deny unknown permissions by default (never grant implicitly)
  return false;
}
