// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/super-admin/SuperAdminPro.tsx": () => import("../components/mockups/super-admin/SuperAdminPro.tsx"),
  "./components/mockups/split-payment/SplitPayMockup.tsx": () => import("../components/mockups/split-payment/SplitPayMockup.tsx")
};
