kind = "web"
  previewPath = "/muhkam-advanced/"
  title = "MUHKAM ADVANCED"
  version = "1.0.0"
  id = "artifacts/muhkam-base"
  router = "path"

  [[integratedSkills]]
  name = "react-vite"
  version = "1.0.0"

  [[services]]
  name = "web"
  paths = [ "/muhkam-advanced/" ]
  localPort = 19990

  [services.development]
  run = "pnpm --filter @workspace/muhkam-pro run dev"

  [services.production]
  build = [ "pnpm", "--filter", "@workspace/muhkam-pro", "run", "build" ]
  publicDir = "artifacts/muhkam-base/dist/public"
  serve = "static"

  [[services.production.rewrites]]
  from = "/*"
  to = "/index.html"

  [services.env]
  PORT = "19990"
  BASE_PATH = "/muhkam-advanced/"
  